# Generated by Django 4.2.5 on 2023-09-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_ly',
            name='userjobseeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.jobseekerprofile'),
            preserve_default=False,
        ),
    ]
