# Generated by Django 4.2.5 on 2023-09-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobseekerprofile_expected_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_ly',
            name='email',
            field=models.EmailField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
