# Generated by Django 4.2.5 on 2023-09-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_app_ly_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='email',
            field=models.EmailField(default=1, max_length=350),
            preserve_default=False,
        ),
    ]
